"""
Reporly — DOCX Report Exporter
Generates professional Word document from Report dataclass.
"""
import io
import logging
from datetime import datetime

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn

from src.templates import get_template

logger = logging.getLogger(__name__)


def _hex_to_rgb(hex_color: str) -> RGBColor:
    """Convert hex color string to RGBColor."""
    h = hex_color.lstrip("#")
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _set_cell_shading(cell, hex_color: str):
    """Set background color of a table cell."""
    shading = cell._element.get_or_add_tcPr()
    shading_elm = shading.makeelement(
        qn("w:shd"),
        {qn("w:fill"): hex_color.lstrip("#"), qn("w:val"): "clear"},
    )
    shading.append(shading_elm)


def export_docx(report, template_name: str = "minimal", app_name: str = "Reporly") -> bytes:
    """
    Export Report to DOCX bytes.

    Args:
        report: Report dataclass (from core.models)
        template_name: Template style name
        app_name: App name for branding

    Returns:
        DOCX file as bytes
    """
    tmpl = get_template(template_name)
    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = tmpl.font_body
    font.size = Pt(tmpl.font_size_body)

    # --- Title Page ---
    _add_title_page(doc, report, tmpl)

    # --- Data Overview ---
    _add_data_overview(doc, report.data_profile, tmpl)

    # --- Key Insights ---
    if report.insights:
        _add_insights(doc, report.insights, tmpl)

    # --- Charts ---
    if report.charts:
        _add_charts(doc, report.charts, tmpl)

    # --- Footer ---
    doc.add_paragraph()
    footer_p = doc.add_paragraph()
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_p.add_run(
        f"Generated by {app_name}  |  {report.generated_at.strftime('%Y-%m-%d %H:%M')}"
    )
    run.font.size = Pt(tmpl.font_size_caption)
    run.font.color.rgb = _hex_to_rgb("#9CA3AF")

    buf = io.BytesIO()
    doc.save(buf)
    docx_bytes = buf.getvalue()

    logger.info("DOCX exported: %.1f KB", len(docx_bytes) / 1024)
    return docx_bytes


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _add_title_page(doc, report, tmpl):
    """Title page with report name, filename, date."""
    # Spacing before title
    for _ in range(4):
        doc.add_paragraph()

    # Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title_p.add_run(report.title)
    run.font.size = Pt(tmpl.font_size_title)
    run.font.name = tmpl.font_heading
    run.bold = True
    run.font.color.rgb = _hex_to_rgb(tmpl.primary_color)

    # Subtitle
    sub_p = doc.add_paragraph()
    run = sub_p.add_run(
        f"{report.data_profile.filename}  |  "
        f"{report.data_profile.rows:,} rows x {report.data_profile.columns} columns"
    )
    run.font.size = Pt(12)
    run.font.color.rgb = _hex_to_rgb(tmpl.secondary_color)

    # Date
    date_p = doc.add_paragraph()
    run = date_p.add_run(report.generated_at.strftime("%Y-%m-%d %H:%M"))
    run.font.size = Pt(11)
    run.font.color.rgb = _hex_to_rgb(tmpl.secondary_color)

    doc.add_page_break()


def _add_data_overview(doc, profile, tmpl):
    """Data overview section with summary table and column details."""
    heading = doc.add_heading("Data Overview", level=1)
    for run in heading.runs:
        run.font.color.rgb = _hex_to_rgb(tmpl.primary_color)
        run.font.name = tmpl.font_heading

    # Summary table
    rows_data = [
        ("Total Rows", f"{profile.rows:,}"),
        ("Total Columns", str(profile.columns)),
        ("Numeric Columns", str(profile.basic_stats.get("numeric_columns", 0))),
        ("Categorical Columns", str(profile.basic_stats.get("categorical_columns", 0))),
        ("Missing Values", f"{profile.basic_stats.get('total_nulls', 0):,} ({profile.basic_stats.get('null_pct', 0)}%)"),
        ("Memory Size", f"{profile.basic_stats.get('memory_mb', 0)} MB"),
    ]

    table = doc.add_table(rows=len(rows_data) + 1, cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.style = "Table Grid"

    # Header row
    for c, text in enumerate(["Metric", "Value"]):
        cell = table.rows[0].cells[c]
        cell.text = text
        _set_cell_shading(cell, tmpl.primary_color)
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.font.size = Pt(10)

    # Data rows
    for r, (metric, value) in enumerate(rows_data, 1):
        table.rows[r].cells[0].text = metric
        table.rows[r].cells[1].text = value
        for c in range(2):
            for p in table.rows[r].cells[c].paragraphs:
                for run in p.runs:
                    run.font.size = Pt(10)

    doc.add_paragraph()

    # Column details
    sub_heading = doc.add_heading("Column Details", level=2)
    for run in sub_heading.runs:
        run.font.color.rgb = _hex_to_rgb(tmpl.secondary_color)

    col_info = profile.column_info[:20]
    if col_info:
        ct = doc.add_table(rows=len(col_info) + 1, cols=4)
        ct.alignment = WD_TABLE_ALIGNMENT.LEFT
        ct.style = "Table Grid"

        for c, text in enumerate(["Column", "Type", "Unique", "Nulls"]):
            cell = ct.rows[0].cells[c]
            cell.text = text
            _set_cell_shading(cell, tmpl.secondary_color)
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.bold = True
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.font.size = Pt(9)

        for r, ci in enumerate(col_info, 1):
            ct.rows[r].cells[0].text = ci.name[:25]
            ct.rows[r].cells[1].text = ci.dtype
            ct.rows[r].cells[2].text = str(ci.unique_count)
            ct.rows[r].cells[3].text = f"{ci.null_pct}%"
            for c in range(4):
                for p in ct.rows[r].cells[c].paragraphs:
                    for run in p.runs:
                        run.font.size = Pt(9)


def _add_insights(doc, insights, tmpl):
    """Key insights section."""
    doc.add_paragraph()
    heading = doc.add_heading("Key Insights", level=1)
    for run in heading.runs:
        run.font.color.rgb = _hex_to_rgb(tmpl.primary_color)
        run.font.name = tmpl.font_heading

    importance_colors = {"high": "#DC2626", "medium": "#D97706", "low": "#059669"}

    for i, insight in enumerate(insights, 1):
        color = importance_colors.get(insight.importance, "#6B7280")

        p = doc.add_paragraph()
        # Importance badge
        badge = p.add_run(f"[{insight.importance.upper()}] ")
        badge.font.size = Pt(9)
        badge.bold = True
        badge.font.color.rgb = _hex_to_rgb(color)

        # Title
        title_run = p.add_run(f"{i}. {insight.title}")
        title_run.bold = True
        title_run.font.size = Pt(11)
        title_run.font.color.rgb = _hex_to_rgb("#1F2937")

        # Description
        desc_p = doc.add_paragraph()
        desc_run = desc_p.add_run(insight.description)
        desc_run.font.size = Pt(10)
        desc_run.font.color.rgb = _hex_to_rgb("#6B7280")
        desc_p.paragraph_format.left_indent = Cm(1)


def _add_charts(doc, charts, tmpl):
    """Embed chart images."""
    doc.add_paragraph()
    heading = doc.add_heading("Visualizations", level=1)
    for run in heading.runs:
        run.font.color.rgb = _hex_to_rgb(tmpl.primary_color)
        run.font.name = tmpl.font_heading

    for chart_bytes in charts:
        img_stream = io.BytesIO(chart_bytes)
        doc.add_picture(img_stream, width=Inches(6))
        doc.add_paragraph()
