"""
Reporly — PDF Report Exporter
Generates professional PDF report from Report dataclass.
Uses ReportLab for programmatic control.
"""
import io
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle,
    PageBreak, HRFlowable,
)

from src.templates import get_template

logger = logging.getLogger(__name__)


def export_pdf(report, template_name: str = "minimal", app_name: str = "Reporly") -> bytes:
    """
    Export Report to PDF bytes.

    Args:
        report: Report dataclass (from core.models)
        template_name: Template style name
        app_name: App name for branding

    Returns:
        PDF file as bytes
    """
    tmpl = get_template(template_name)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=25 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    _add_custom_styles(styles, tmpl)

    story = []

    # --- Cover section ---
    story.extend(_build_cover(report, styles, app_name))
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    story.append(Spacer(1, 15))

    # --- Data Overview ---
    story.extend(_build_data_overview(report.data_profile, styles))
    story.append(Spacer(1, 15))

    # --- Data Quality Warnings ---
    if report.data_profile.warnings:
        story.extend(_build_warnings(report.data_profile.warnings, styles))
        story.append(Spacer(1, 15))

    # --- AI Insights ---
    if report.insights:
        story.extend(_build_insights(report.insights, styles))
        story.append(Spacer(1, 15))

    # --- Charts ---
    if report.charts:
        story.extend(_build_charts(report.charts, styles))

    # --- Footer ---
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#D1D5DB")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"Generated by {app_name} · {report.generated_at.strftime('%Y-%m-%d %H:%M')}",
        styles["Footer"],
    ))

    doc.build(story)
    pdf_bytes = buf.getvalue()

    logger.info("PDF exported: %.1f KB", len(pdf_bytes) / 1024)
    return pdf_bytes


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _build_cover(report, styles, app_name: str) -> list:
    """Build cover/title section."""
    return [
        Spacer(1, 40),
        Paragraph(report.title, styles["ReportTitle"]),
        Spacer(1, 8),
        Paragraph(
            f"{report.data_profile.filename} · "
            f"{report.data_profile.rows:,} rows × {report.data_profile.columns} columns",
            styles["Subtitle"],
        ),
        Spacer(1, 30),
    ]


def _build_data_overview(profile, styles) -> list:
    """Build data overview table."""
    elements = [Paragraph("Data Overview", styles["SectionTitle"])]
    elements.append(Spacer(1, 8))

    # Summary stats table
    data = [
        ["Metric", "Value"],
        ["Total Rows", f"{profile.rows:,}"],
        ["Total Columns", str(profile.columns)],
        ["Numeric Columns", str(profile.basic_stats.get("numeric_columns", 0))],
        ["Categorical Columns", str(profile.basic_stats.get("categorical_columns", 0))],
        ["Missing Values", f"{profile.basic_stats.get('total_nulls', 0):,} ({profile.basic_stats.get('null_pct', 0)}%)"],
        ["Memory Size", f"{profile.basic_stats.get('memory_mb', 0)} MB"],
    ]

    table = Table(data, colWidths=[150, 200])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(table)

    # Column details
    elements.append(Spacer(1, 15))
    elements.append(Paragraph("Column Details", styles["SubsectionTitle"]))
    elements.append(Spacer(1, 5))

    col_data = [["Column", "Type", "Unique", "Nulls", "Sample"]]
    for ci in profile.column_info[:20]:  # Max 20 columns in table
        sample = ", ".join(str(v) for v in ci.sample_values[:3])
        if len(sample) > 40:
            sample = sample[:37] + "..."
        col_data.append([
            ci.name[:25], ci.dtype, str(ci.unique_count),
            f"{ci.null_pct}%", sample,
        ])

    col_table = Table(col_data, colWidths=[100, 70, 50, 50, 180])
    col_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#374151")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(col_table)

    return elements


def _build_warnings(warnings: list[str], styles) -> list:
    """Build data quality warnings section."""
    elements = [Paragraph("⚠ Data Quality Notes", styles["SectionTitle"])]
    elements.append(Spacer(1, 5))
    for w in warnings:
        elements.append(Paragraph(f"• {w}", styles["BodyCustom"]))
    return elements


def _build_insights(insights: list, styles) -> list:
    """Build AI insights section."""
    elements = [Paragraph("Key Insights", styles["SectionTitle"])]
    elements.append(Spacer(1, 8))

    importance_colors = {"high": "#DC2626", "medium": "#D97706", "low": "#059669"}

    for i, insight in enumerate(insights, 1):
        color = importance_colors.get(insight.importance, "#6B7280")
        elements.append(Paragraph(
            f'<font color="{color}">●</font> '
            f'<b>{i}. {insight.title}</b> '
            f'<font color="#9CA3AF" size="8">[{insight.importance}]</font>',
            styles["BodyCustom"],
        ))
        elements.append(Paragraph(insight.description, styles["InsightBody"]))
        elements.append(Spacer(1, 8))

    return elements


def _build_charts(charts: list[bytes], styles) -> list:
    """Embed chart images in PDF."""
    elements = [Paragraph("Visualizations", styles["SectionTitle"])]
    elements.append(Spacer(1, 10))

    for chart_bytes in charts:
        img_buf = io.BytesIO(chart_bytes)
        img = Image(img_buf, width=450, height=280)
        elements.append(img)
        elements.append(Spacer(1, 15))

    return elements


# ---------------------------------------------------------------------------
# Custom styles
# ---------------------------------------------------------------------------

def _add_custom_styles(styles, tmpl):
    """Register custom paragraph styles using template colors/fonts."""
    bold_heading = tmpl.font_heading
    if bold_heading == "Helvetica":
        bold_heading = "Helvetica-Bold"
    elif bold_heading == "Times-Roman":
        bold_heading = "Times-Bold"

    styles.add(ParagraphStyle(
        name="ReportTitle", fontSize=tmpl.font_size_title, leading=tmpl.font_size_title + 6,
        alignment=TA_LEFT, fontName=bold_heading,
        textColor=tmpl.primary_color,
    ))
    styles.add(ParagraphStyle(
        name="Subtitle", fontSize=11, leading=16,
        alignment=TA_LEFT, textColor=tmpl.secondary_color,
        fontName=tmpl.font_body,
    ))
    styles.add(ParagraphStyle(
        name="SectionTitle", fontSize=tmpl.font_size_heading, leading=tmpl.font_size_heading + 4,
        fontName=bold_heading, textColor=tmpl.primary_color,
        spaceBefore=10,
    ))
    styles.add(ParagraphStyle(
        name="SubsectionTitle", fontSize=11, leading=15,
        fontName=bold_heading, textColor=tmpl.secondary_color,
    ))
    styles.add(ParagraphStyle(
        name="BodyCustom", fontSize=tmpl.font_size_body, leading=tmpl.font_size_body + 4,
        textColor="#374151", fontName=tmpl.font_body,
    ))
    styles.add(ParagraphStyle(
        name="InsightBody", fontSize=tmpl.font_size_body - 1, leading=tmpl.font_size_body + 3,
        textColor=tmpl.secondary_color, leftIndent=18, fontName=tmpl.font_body,
    ))
    styles.add(ParagraphStyle(
        name="Footer", fontSize=tmpl.font_size_caption, leading=tmpl.font_size_caption + 2,
        alignment=TA_CENTER, textColor="#9CA3AF", fontName=tmpl.font_body,
    ))
